using EY.UbbstractThinkers.ProjectManagementPortal.Server.Data;
using EY.UbbstractThinkers.ProjectManagementPortal.Server.Exceptions;
using EY.UbbstractThinkers.ProjectManagementPortal.Server.Models;
using EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Validators;
using EY.UbbstractThinkers.ProjectManagementPortal.Server.Repositories;
using EY.UbbstractThinkers.ProjectManagementPortal.Server.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EY.UbbstractThinkers.ProjectManagementPortal.Server.Services
{
    public class ProjectService : IProjectService
    {
        private readonly IRepository _repository;
        private readonly AppDbContext _context;
        private readonly IProjectValidator _projectValidator;
        private readonly UserManager<User> _userManager;
        private readonly IHttpContextAccessor _accesor;

        public ProjectService(IRepository repository, AppDbContext context, IProjectValidator projectValidator, ILogger<ProjectService> logger, UserManager<User> userManager, IHttpContextAccessor accesor)
        {
            _repository = repository;
            _context = context;
            _projectValidator = projectValidator;
            _userManager = userManager;
            _accesor = accesor;
        }

        public async Task<IEnumerable<Project>> GetProjects()
        {
            return await _repository.GetProjects();
        }

        public async Task<Project> GetProject(Guid id)
        {
            var project = await _repository.GetProject(id);

            if (project == null)
            {
                return null;
            }

            return project;
        }

        public async Task<Project> SaveProject(Project project)
        {
            if (project.Uid != Guid.Empty)
            {
                throw new ApiException(ErrorMessageConstants.AutoGeneratedId);
            }

            var owner = await _userManager.FindByIdAsync(project.OwnerId);

            if (project.OwnerId == null || owner == null)
            {
                throw new ApiException(ErrorMessageConstants.ProjectOwnerUnavailable);
            }

            if (await _repository.GetProjectByName(project.Name) != null)
            {
                throw new ApiException(ErrorMessageConstants.ProjectNameNotUniqueMessage);
            }

            var projectValidationResults = _projectValidator.Validate(new ValidationContext(project));

            if (projectValidationResults.Any())
            {
                throw new ApiException(string.Join(", ", projectValidationResults));
            }

            await _context.Projects.AddAsync(project);
            await _context.SaveChangesAsync();

            return project;
        }

        public async Task DeleteProject(Project project)
        {

            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
        }

        public async Task<Project> UpdateProject(Guid id, Project project)
        {
            var existingProject = await _repository.GetProject(id);

            if (existingProject == null)
            {
                return null;
            }

            var owner = await _userManager.FindByIdAsync(project.OwnerId);

            if (project.OwnerId == null || owner == null)
            {
                throw new ApiException(ErrorMessageConstants.ProjectOwnerUnavailable);
            }

            var existingProjectByName = await _repository.GetProjectByName(project.Name);

            if (existingProjectByName != null && existingProject.Uid != existingProjectByName.Uid)
            {
                throw new ApiException(ErrorMessageConstants.ProjectNameNotUniqueMessage);
            }

            var projectValidationResults = _projectValidator.Validate(new ValidationContext(project));

            if (projectValidationResults.Any())
            {
                throw new ApiException(string.Join(", ", projectValidationResults));
            }

            existingProject.Name = project.Name;
            existingProject.Description = project.Description;
            existingProject.StartDate = project.StartDate;
            existingProject.EndDate = project.EndDate;
            await _context.SaveChangesAsync();

            return project;
        }

        public async Task<Project> SaveStakeholders(Project project, List<string> stakeholderIds)
        {
            User loggedUser = await _userManager.FindByEmailAsync(_accesor.HttpContext.User.FindFirstValue(ClaimTypes.Email));

            if (loggedUser.Id != project.OwnerId)
            {
                throw new ApiException(ErrorMessageConstants.NotAnOwner);
            }

            foreach (var id in stakeholderIds)
            {
                if (await _userManager.FindByIdAsync(id) == null)
                {
                    throw new ApiException(ErrorMessageConstants.InexistentUser);
                }

                if (project.OwnerId == id)
                {
                    throw new ApiException(ErrorMessageConstants.OwnerIsStakeholder);
                }

                var stakeholderProject = new ProjectStakeholder
                {
                    ProjectId = project.Uid,
                    UserId = id
                };
                _context.ProjectStakeholders.Add(stakeholderProject);
            }

            await _context.SaveChangesAsync();

            return project;
        }

        public async Task<Project> SaveResources(Project project, List<string> resourceIds)
        {
            User loggedUser = await _userManager.FindByEmailAsync(_accesor.HttpContext.User.FindFirstValue(ClaimTypes.Email));

            if (loggedUser.Id != project.OwnerId)
            {
                throw new ApiException(ErrorMessageConstants.NotAnOwner);
            }

            foreach (var id in resourceIds)
            {
                if (await _userManager.FindByIdAsync(id) == null)
                {
                    throw new ApiException(ErrorMessageConstants.InexistentUser);
                }

                var stakeholderProject = new ProjectStakeholder
                {
                    ProjectId = project.Uid,
                    UserId = id
                };
                _context.ProjectStakeholders.Add(stakeholderProject);
            }

            await _context.SaveChangesAsync();

            return project;
        }

        public async Task<IEnumerable<Project>> GetProjectsVisibleToUser(string userId)
        {
            var projects = await _repository.GetProjectsVisibleToUser(userId);

            return projects;
        }
    }
}
