namespace EY.UbbstractThinkers.ProjectManagementPortal.Server.Utils
{
    public class ErrorMessageConstants
    {
        public const string ProjectNotFoundMessage = "Project with the given id has not been found";
        public const string ProjectNameNotUniqueMessage = "Project Name must be unique";
        public const string NotMatchingIds = "Project id doesn't match with the given id";
        public const string AutoGeneratedId = "Project id is auto generated";
    }
}
