namespace EY.UbbstractThinkers.ProjectManagementPortal.Server.Utils
{
    public class ErrorMessageConstants
    {
        public const string ProjectNotFoundMessage = "Project with the given id has not been found.";
        public const string ProjectNameNotUniqueMessage = "Project Name must be unique.";
        public const string NotMatchingIds = "Project id doesn't match with the given id.";
        public const string AutoGeneratedId = "Project id is auto generated.";
        public const string ProjectOwnerUnavailable = "Project Owner must be a user in the application.";
        public const string OwnerIsStakeholder = "Owner can't be a stakeholder.";
        public const string NotAnOwner = "You must be an owner to do this action.";
        public const string InexistentUser = "Can't use a inexistent user.";
        public const string InexistentTemplate = "Project template does not exist.";
        public const string InexistentStage = "A stage does not exist.";
        public const string CommonError = "An error occurred.";
        public const string CurrentStageChangeError = "Can't change current state without approval.";
        public const string TemplateChangeError = "Can't change project template.";
        public const string OnlyOnePendingApprovalRequest = "Project already has pending approval request.";
        public const string UnableToChangeStage = "Unable to change stage in current state.";
        public const string LoggedUserNotAStakeholder = "Approval requests can only be edited by stakeholders of a project.";
        public const string OnlyPendingApprovalRequests = "Only pending approval requests can be approved or rejected.";
        public const string CantChangeStateToPending = "Can't change the state to Pending.";
        public const string NotAValidStatusType = "Status must have a valid value.";
        public const string InvalidTaskTimeline = "Task timeline must be inside project timeline.";
        public const string InvalidProjectTimeline = "Project timeline must include all task timelines.";
        public const string InvalidResource = "Resource does not exist for this project.";
        public const string CantChangeProjectTask = "Cannot change project for a task.";
        public const string UniqueResource = "Can't add the same resource more than one time.";
        public const string UniqueStakeholder = "Can't add the same stakeholder more than one time.";
        public const string TemplateHasExistingProjects = "Can't change templates that have active projects.";
        public const string InexistentCustomField = "Can't use a inexistent custom field.";
        public const string TextValueError = "Field Text Value can't more than 500 characters.";
        public const string DateValueError = "Field Date Value must be in correct format.";
        public const string TemplateNotMatching = "Project and Custom Field must have the same template.";
        public const string CustomFieldValueVisibleStages = "Can't change value on project's current stage.";
        public const string NoVisibleStages = "Custom Field must have at least one visible stage.";
        public const string TemplateHasExistingCustomFields = "Can't change templates that have active custom fields visible to stage.";
        public const string DifferentProjectId = "Can only update values on one project.";
        public const string TemplateChangeErrorCustomField = "Can't change custom field template.";
        public const string TypeChangeError = "Can't change custom field type.";
    }
}
