namespace EY.UbbstractThinkers.ProjectManagementPortal.Server.Utils
{
    public class ErrorMessageConstants
    {
        public const string ProjectNotFoundMessage = "Project with the given id has not been found.";
        public const string ProjectNameNotUniqueMessage = "Project Name must be unique.";
        public const string NotMatchingIds = "Project id doesn't match with the given id.";
        public const string AutoGeneratedId = "Project id is auto generated.";
        public const string ProjectOwnerUnavailable = "Project Owner must be a user in the application.";
        public const string OwnerIsStakeholder = "Owner can't be a stakeholder.";
        public const string NotAnOwner = "You must be an owner to do this action.";
        public const string InexistentUser = "Can't use a inexistent user.";
    }
}
