// <auto-generated />
using System;
using EY.UbbstractThinkers.ProjectManagementPortal.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EY.UbbstractThinkers.ProjectManagementPortal.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826112152_StageSeeding")]
    partial class StageSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FromStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Uid");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ToStageId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomField", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("TemplateId");

                    b.ToTable("CustomFields");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomFieldValue", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId", "CustomFieldId");

                    b.HasIndex("CustomFieldId")
                        .IsUnique();

                    b.ToTable("CustomFieldValues");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CurrentStageUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TemplateUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Uid");

                    b.HasIndex("CurrentStageUid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TemplateUid");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ProjectResource", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectId", "UserId");

                    b.ToTable("ProjectResources");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ProjectStakeholder", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectId", "UserId");

                    b.ToTable("ProjectStakeholders");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ProjectUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("ProjectUid");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Stage", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("2402bf5a-48a2-411e-b226-ee7cc32f1c84"),
                            Description = "Initiate the project",
                            Name = "Initiate",
                            OrderNumber = 1
                        },
                        new
                        {
                            Uid = new Guid("3a38e6e3-b685-49ac-a64c-a0a2574c2a41"),
                            Description = "Plan the project",
                            Name = "Plan",
                            OrderNumber = 2
                        },
                        new
                        {
                            Uid = new Guid("45faf5b0-4af5-45f8-bda1-79c14498dfbd"),
                            Description = "Execute the project",
                            Name = "Execute",
                            OrderNumber = 3
                        },
                        new
                        {
                            Uid = new Guid("b5d06184-6d8d-4dee-b310-ace6906e9882"),
                            Description = "Monitor the project",
                            Name = "Monitor",
                            OrderNumber = 4
                        },
                        new
                        {
                            Uid = new Guid("7402e745-2eac-4d68-81f1-236cc1ba23d7"),
                            Description = "Close the project",
                            Name = "Close",
                            OrderNumber = 5
                        });
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Template", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Uid");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.TemplateStage", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplateId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("TemplateStage");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.TemplateStageCustomField", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplateId", "StageId", "CustomFieldId");

                    b.HasIndex("CustomFieldId");

                    b.ToTable("TemplateStageCustomField");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ApprovalRequest", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Stage", "FromStage")
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", "Project")
                        .WithMany("Approvals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Stage", "ToStage")
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("Project");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomField", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Template", "Template")
                        .WithMany("CustomFields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomFieldValue", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomField", "CustomField")
                        .WithOne("CustomFieldValue")
                        .HasForeignKey("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomFieldValue", "CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Stage", "CurrentStage")
                        .WithMany("Projects")
                        .HasForeignKey("CurrentStageUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Template", "Template")
                        .WithMany("Projects")
                        .HasForeignKey("TemplateUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStage");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ProjectResource", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", null)
                        .WithMany("Resources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ProjectStakeholder", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", null)
                        .WithMany("Stakeholders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.ProjectTask", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.TemplateStage", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.TemplateStageCustomField", b =>
                {
                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.TemplateStage", "TemplateStage")
                        .WithMany()
                        .HasForeignKey("TemplateId", "StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("TemplateStage");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.CustomField", b =>
                {
                    b.Navigation("CustomFieldValue");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Project", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Resources");

                    b.Navigation("Stakeholders");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Stage", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EY.UbbstractThinkers.ProjectManagementPortal.Server.Models.Template", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
